---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-cluster-metrics
  namespace: observability
spec:
  mode: deployment
  replicas: 1
  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      memory: 64Mi
  env:
    - name: GRAFANA_CLOUD_BASIC_AUTH_HEADER
      valueFrom:
        secretKeyRef:
          name: grafanacloud-key
          key: GRAFANA_CLOUD_BASIC_AUTH_HEADER
    - name: GRAFANA_CLOUD_OTLP_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: grafanacloud-key
          key: GRAFANA_CLOUD_OTLP_ENDPOINT
  config:
    receivers:
      k8s_cluster:
        collection_interval: 30s
        node_conditions_to_report:
          - Ready
          - MemoryPressure
          - DiskPressure
          - PIDPressure
        allocatable_types_to_report:
          - cpu
          - memory
        metrics:
          # Disable metrics that duplicate kube-state-metrics
          k8s.container.cpu_limit:
            enabled: false
          k8s.container.cpu_request:
            enabled: false
          k8s.container.memory_limit:
            enabled: false
          k8s.container.memory_request:
            enabled: false
          k8s.container.ready:
            enabled: false
          k8s.container.restarts:
            enabled: false
          k8s.daemonset.current_scheduled_nodes:
            enabled: false
          k8s.daemonset.desired_scheduled_nodes:
            enabled: false
          k8s.daemonset.misscheduled_nodes:
            enabled: false
          k8s.daemonset.ready_nodes:
            enabled: false
          k8s.deployment.available:
            enabled: false
          k8s.deployment.desired:
            enabled: false
          k8s.namespace.phase:
            enabled: false
          k8s.pod.phase:
            enabled: false
          k8s.replicaset.available:
            enabled: false
          k8s.replicaset.desired:
            enabled: false
          k8s.statefulset.current_pods:
            enabled: false
          k8s.statefulset.desired_pods:
            enabled: false
          k8s.statefulset.ready_pods:
            enabled: false
          k8s.statefulset.updated_pods:
            enabled: false
    processors:
      transform/cluster:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["cluster"], "ignikube")
      batch: {}
    exporters:
      otlp_http/grafanacloud-metrics:
        endpoint: '${GRAFANA_CLOUD_OTLP_ENDPOINT}/otlp'
        headers:
          authorization: '${GRAFANA_CLOUD_BASIC_AUTH_HEADER}'
    service:
      pipelines:
        metrics:
          receivers: [k8s_cluster]
          processors: [transform/cluster, batch]
          exporters: [otlp_http/grafanacloud-metrics]
