---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: daemonset
  targetAllocator:
    enabled: true
    allocationStrategy: per-node
    prometheusCR:
      enabled: true
      serviceMonitorSelector: {}
      podMonitorSelector: {}
  volumeMounts:
    - name: varlogpods
      mountPath: /var/log/pods
      readOnly: true
  volumes:
    - name: varlogpods
      hostPath:
        path: /var/log/pods
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: GRAFANA_CLOUD_BASIC_AUTH_HEADER
      valueFrom:
        secretKeyRef:
          name: grafanacloud-key
          key: GRAFANA_CLOUD_BASIC_AUTH_HEADER
    - name: GRAFANA_CLOUD_OTLP_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: grafanacloud-key
          key: GRAFANA_CLOUD_OTLP_ENDPOINT
  config:
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 30s
          scrape_configs:
            - job_name: kubelet-cadvisor
              scheme: https
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              metrics_path: /metrics/cadvisor
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: replace
                  source_labels: [__meta_kubernetes_node_name]
                  target_label: node
              metric_relabel_configs:
                - source_labels: [container]
                  regex: 'POD'
                  action: drop
                - source_labels: [__name__]
                  regex: 'container_(cpu_usage_seconds_total|cpu_cfs_throttled_periods_total|cpu_cfs_periods_total|memory_working_set_bytes|memory_usage_bytes|network_receive_bytes_total|network_transmit_bytes_total|fs_reads_bytes_total|fs_writes_bytes_total)|machine_memory_bytes'
                  action: keep
                - regex: 'id'
                  action: labeldrop
      otlp:
        protocols:
          grpc: {}
          http: {}
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/observability_otel-*/**
        include_file_path: true
        include_file_name: false
        operators:
          - type: router
            id: get-format
            routes:
              - output: parser-containerd
                expr: 'body matches "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}"'
          - type: regex_parser
            id: parser-containerd
            regex: '^(?P<time>[^ ]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%f%j'
          - type: move
            from: attributes.log
            to: body
          - type: move
            from: attributes.stream
            to: attributes["log.iostream"]
          - type: remove
            field: attributes.logtag
    processors:
      batch: {}
      transform/cluster:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["cluster"], "ignikube")
      resource/logs:
        attributes:
          - action: insert
            key: loki.format
            value: raw
          - action: insert
            key: k8s.cluster.name
            value: ignikube
      k8s_attributes:
        auth_type: serviceAccount
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.pod.name
            - k8s.node.name
            - k8s.container.name
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: connection
      resourcedetection:
        detectors: [env, system]
        timeout: 5s
        override: false
    exporters:
      otlp_http/grafanacloud-metrics:
        endpoint: '${GRAFANA_CLOUD_OTLP_ENDPOINT}/otlp'
        headers:
          authorization: '${GRAFANA_CLOUD_BASIC_AUTH_HEADER}'
      otlp_http/grafanacloud-traces:
        endpoint: '${GRAFANA_CLOUD_OTLP_ENDPOINT}/otlp'
        headers:
          authorization: '${GRAFANA_CLOUD_BASIC_AUTH_HEADER}'
      otlp_http/grafanacloud-logs:
        endpoint: '${GRAFANA_CLOUD_OTLP_ENDPOINT}/otlp'
        headers:
          authorization: '${GRAFANA_CLOUD_BASIC_AUTH_HEADER}'
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors:
            [k8s_attributes, resourcedetection, transform/cluster, batch]
          exporters: [otlp_http/grafanacloud-metrics]
        traces:
          receivers: [otlp]
          processors: [k8s_attributes, resourcedetection, batch]
          exporters: [otlp_http/grafanacloud-traces]
        logs:
          receivers: [filelog]
          processors: [k8s_attributes, resource/logs, resourcedetection, batch]
          exporters: [otlp_http/grafanacloud-logs]
