---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafanacloud-key
  namespace: observability
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless

  target:
    name: grafanacloud-key
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: /grafanacloud-key
