---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: star-fuochi-top
  namespace: cilium
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.1.16
  listeners:
    - name: https
      hostname: '*.fuochi.top'
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: star-fuochi-top-tls
            namespace: cilium
            kind: Secret
            group: ''
