---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-series
mountOptions:
  - hard
  - nfsvers=4.2
parameters:
  mountPermissions: '0'
  server: nas.fuochi.top
  share: /series
  subDir: ${pvc.metadata.name}
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
