---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets-operator
            name: universal-auth-credentials
          clientSecret:
            key: clientSecret
            namespace: external-secrets-operator
            name: universal-auth-credentials
      secretsScope:
        projectSlug: ignikube
        environmentSlug: prod
        secretsPath: /
        recursive: false
        expandSecretReferences: false # Default is true
