---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: akeyless
spec:
  provider:
    akeyless:
      akeylessGWApiURL: 'https://api.akeyless.io'
      authSecretRef:
        secretRef:
          accessID:
            name: eso-credentials
            namespace: external-secrets-operator
            key: accessId
          accessType:
            name: eso-credentials
            namespace: external-secrets-operator
            key: accessType
          accessTypeParam:
            name: eso-credentials
            namespace: external-secrets-operator
            key: accessTypeParam
