---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: universal-auth-credentials
  namespace: external-secrets-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: universal-auth-credentials

  data:
    - secretKey: clientId
      remoteRef:
        key: /eso/clientId
    - secretKey: clientSecret
      remoteRef:
        key: /eso/clientSecret
