---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-credentials
  namespace: external-secrets-operator
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless

  target:
    name: eso-credentials
    creationPolicy: Owner

  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: /ignikube
        metadataPolicy: None
