---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: jellyfin
spec:
  storageClassName: nfs-movies
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Ti
