---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: series
  namespace: jellyfin
spec:
  storageClassName: nfs-series
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2.5Ti
