---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcoding
  namespace: jellyfin
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
