---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless

  target:
    name: cloudflare-api-token
    creationPolicy: Owner

  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /cloudflare-api
        metadataPolicy: None
