apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  appName: cloudflare-api
  destination:
    create: true
    name: cloudflare-api-token
  refreshAfter: 1h
