---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-operator-token
  namespace: observability
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless

  target:
    name: grafana-operator-token
    creationPolicy: Owner

  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: /grafana-operator-token
        metadataPolicy: None
