---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebook-library
  namespace: calibre
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
