---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-library
  namespace: immich
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
