---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-pg-user
  namespace: immich
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless

  target:
    name: immich-pg-user
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: /immich-pg-user
