---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-config
  namespace: plex
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
