---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cnpg-creds
  namespace: cnpg-system
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless

  target:
    name: garage-cnpg-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: 'true'
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: /garage-cnpg
        metadataPolicy: None
        nullBytePolicy: Ignore
