---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: cloudflare-token
  namespace: cloudflare
spec:
  appName: cloudflare-tunnel
  destination:
    create: true
    name: cloudflare-tunnel-remote
  refreshAfter: 1h
