---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: cloudflare
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless

  target:
    name: cloudflare-tunnel-remote
    creationPolicy: Owner

  data:
    - secretKey: tunnelToken
      remoteRef:
        key: /cloudflare-tunnel
