apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: vso-sp
  namespace: vso
spec:
  appName: ignikube
  destination:
    create: true
    name: vso-sp
  refreshAfter: 1h
