---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: vso-sp
  namespace: vault-secrets-operator
spec:
  appName: ignikube
  destination:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
    create: true
    name: vso-sp
  refreshAfter: 1h
