---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-immich
  namespace: cnpg-system
spec:
  name: immich
  owner: immich
  cluster:
    name: cloudnative-pg-cluster
  extensions:
    - name: vector
      ensure: present
    - name: cube
      ensure: present
    - name: vchord
      ensure: present
      version: 0.3.0
    - name: earthdistance
      ensure: present
