---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-immich
  namespace: cnpg-system
spec:
  name: immich
  owner: immich
  cluster:
    name: cloudnative-pg-cluster
  extensions:
    - name: vchord
    - name: earthdistance
