---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-prowlarr-log
  namespace: cnpg-system
spec:
  name: prowlarr-log
  owner: prowlarr
  cluster:
    name: cloudnative-pg-cluster
