---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-prowlarr-main
  namespace: cnpg-system
spec:
  name: prowlarr-main
  owner: prowlarr
  cluster:
    name: cloudnative-pg-cluster
