---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-pg-user
  namespace: cnpg-system
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless

  target:
    name: immich-pg-user
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: 'true'
  dataFrom:
    - extract:
        key: /immich-pg-user
