---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: immich-pg-user
  namespace: cnpg-system
spec:
  appName: immich-pg-user
  destination:
    type: kubernetes.io/basic-auth
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: immich
    labels:
      cnpg.io/reload: 'true'
    create: true
    name: immich-pg-user
  refreshAfter: 1h
