---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-pg-user
  namespace: cnpg-system
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless

  target:
    name: cloudflare-tunnel-remote
    creationPolicy: Owner
    template:
      metadata:
        annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: immich
      labels:
        cnpg.io/reload: 'true'
  dataFrom:
    - extract:
        key: /immich-pg-user
