---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-state-metrics
      targetRevision: 7.2.2
      helm:
        releaseName: kube-state-metrics
        valuesObject:
          collectors:
            - daemonsets
            - deployments
            - namespaces
            - nodes
            - pods
            - replicasets
            - statefulsets
          prometheus:
            monitor:
              enabled: true
