---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: netbird
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
  sources:
    - repoURL: https://netbirdio.github.io/helms
      chart: kubernetes-operator
      targetRevision: 0.2.2
      helm:
        releaseName: netbird-operator
        valuesObject:
          netbirdAPI:
            keyFromSecret:
              name: 'mgmt-api-key'
              key: 'NB_API_KEY'
          operator:
            resources:
              requests:
                cpu: 4m
                memory: 32Mi
              limits:
                memory: 32Mi
          # renovate: datasource=docker packageName=netbirdio/netbird
          routingClientImage: netbirdio/netbird:0.69.0-rootless

    - repoURL: https://netbirdio.github.io/helms
      chart: netbird-operator-config
      targetRevision: 0.1.0
      helm:
        releaseName: netbird-operator-config
        valuesObject:
          router:
            enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 192Mi
              limits:
                memory: 192Mi

    - repoURL: https://github.com/Fuochi/ignikube.git
      targetRevision: main
      path: apps/netbird
