---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cilium
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
      - ServerSideApply=true
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.18.7
      helm:
        releaseName: cilium
        valuesObject:
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true

          operator:
            replicas: 1
            prometheus:
              enabled: true
              serviceMonitor:
                enabled: true

          envoy:
            # Use custom envoy image for raspberry pi support
            image:
              repository: docker.io/apetutschnig/rpi-cilium-envoy
              tag: 1.35.3
              useDigest: false

          # Certificate managed via cronjob to avoid argocd reconciliation issues
          hubble:
            metrics:
              enabled:
                - dns
                - drop
                - tcp
                - flow
                - icmp
                - http
              serviceMonitor:
                enabled: true
            listenAddress: ':4244'
            relay:
              enabled: true
              resources:
                requests:
                  cpu: 10m
                  memory: 128Mi
                limits:
                  memory: 128Mi
            tls:
              auto:
                method: cronJob
            ui:
              enabled: true
              frontend:
                resources:
                  requests:
                    cpu: 5m
                    memory: 24Mi
                  limits:
                    memory: 24Mi
              backend:
                resources:
                  requests:
                    cpu: 10m
                    memory: 128Mi
                  limits:
                    memory: 128Mi

          kubeProxyReplacement: true
          # K3s proxy api server in localhost:6444 on each node
          k8sServiceHost: 127.0.0.1
          k8sServicePort: 6444

          l2announcements:
            enabled: true
          k8sClientRateLimit:
            qps: 40
            burst: 60

          gatewayAPI:
            enabled: true

          routingMode: native
          autoDirectNodeRoutes: true
          directRoutingSkipUnreachable: true

    - repoURL: https://github.com/Fuochi/ignikube.git
      targetRevision: main
      path: apps/cilium

    - repoURL: https://github.com/kubernetes-sigs/gateway-api
      targetRevision: v1.5.1
      path: config/crd/standard
