---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre-web
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: calibre
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
  source:
    repoURL: https://github.com/Fuochi/ignikube.git
    targetRevision: main
    path: apps/calibre-web
