---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-state-metrics
      targetRevision: 7.2.2
      helm:
        releaseName: kube-state-metrics
        valuesObject:
          collectors:
            - daemonsets
            - deployments
            - namespaces
            - nodes
            - pods
            - replicasets
            - statefulsets
          metricAllowlist:
            - kube_daemonset_status_(desired|ready)_number_scheduled
            - kube_deployment_(status_replicas|spec_replicas)
            - kube_deployment_status_replicas_(available|unavailable|updated)
            - kube_namespace_status_phase
            - kube_node_info
            - kube_node_status_(condition|allocatable|capacity)
            - kube_pod_info
            - kube_pod_owner
            - kube_pod_status_(phase|ready|scheduled)
            - kube_pod_container_(info|status_ready|status_restarts_total)
            - kube_pod_container_resource_(requests|limits)
            - kube_pod_container_status_(running|waiting|terminated)
            - kube_pod_container_status_last_terminated_reason
            - kube_replicaset_owner
            - kube_statefulset_(status_replicas|replicas)
            - kube_statefulset_status_replicas_(ready|updated)
          prometheus:
            monitor:
              enabled: true
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
            limits:
              memory: 48Mi
