---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-node-exporter
      targetRevision: 4.52.2
      helm:
        releaseName: node-exporter
        valuesObject:
          prometheus:
            monitor:
              enabled: true
