---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seerr
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: seerr
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
  sources:
    - repoURL: ghcr.io/seerr-team/seerr
      chart: seerr-chart
      targetRevision: 3.4.1
      helm:
        releaseName: seerr
        valuesObject:
          config:
            persistence:
              storageClass: nfs-csi
          route:
            main:
              enabled: true
              hostnames:
                - seerr.fuochi.top
              parentRefs:
                - name: star-fuochi-top
                  namespace: cilium
                  sectionName: https
