---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-node-exporter
      targetRevision: 4.53.1
      helm:
        releaseName: node-exporter
        valuesObject:
          extraArgs:
            - --collector.disable-defaults
            - --collector.cpu
            - --collector.loadavg
            - --collector.meminfo
            - --collector.filesystem
            - --collector.netdev
            - --collector.diskstats
            - --collector.uname
          prometheus:
            monitor:
              enabled: true
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
            limits:
              memory: 32Mi
