---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault-secrets-operator
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
  sources:
    - chart: vault-secrets-operator
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.10.0
      helm:
        releaseName: vault-secrets-operator
    - repoURL: https://github.com/Fuochi/ignikube.git
      targetRevision: main
      path: apps/vso
