---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
      - ServerSideApply=true
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-operator
      targetRevision: 0.110.0
      helm:
        releaseName: otel-operator
        valuesObject:
          manager:
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 64Mi
            createRbacPermissions: true

    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-operator-crds
      targetRevision: 28.0.1
      helm:
        releaseName: prometheus-operator-crds

    # TODO: check if opentelemetry-collector and/or opentelemetry-target-allocator helm charts can be used instead
    - repoURL: https://github.com/Fuochi/ignikube.git
      targetRevision: main
      path: apps/otel
