---
apiVersion: netbird.io/v1
kind: NBResource
metadata:
  name: calibre
  namespace: netbird
spec:
  address: calibre.fuochi.top
  groups:
    - All
  name: calibre
  networkID: damdehrl0ubs739r3330
